app.storage=memory
app.tree-strategy=custom

spring.datasource.url=jdbc:postgresql://localhost:5432/organigrama_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=organigrama_db